services:
  mc:
    image: itzg/minecraft-server:java17-openj9
    ports:
      - "25565:25565"
    environment:
      # Whitelist
      WHITELIST: "05f9e15f-4ed3-4ecd-b7f7-b9ad1f0a8e58"
      # Mods and datapacks
      VANILLATWEAKS_SHARECODE: "dWuZTL,d4Xleu"
      MODRINTH_PROJECTS: "fabric-api,alternate-current,c2me-fabric,ferrite-core,krypton,lithium,memoryleakfix,starlight,spark,no-chat-reports,terra,fallingtree"
      MODS: "https://github.com/MangoPlex/smp/releases/latest/download/mangoplex-smp-mc${minecraftVersion}.yml"
      # Auto-execute RCON commands
      RCON_CMDS_STARTUP: |-
        scoreboard players set in mt.common_chance 2200
        scoreboard players set in mt.rare_chance 11000
        scoreboard players set in mt.epic_chance 30900
        scoreboard players set in mt.legendary_chance 136000
        
        gamerule disableElytraMovementCheck true
        gamerule playersSleepingPercentage 50
      # Server version
      VERSION: ${minecraftVersion}
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: ${loaderVersion}
      # Server properties
      EULA: true
      DIFFICULTY: hard
      FORCE_GAME_MODE: true
      SNOOPER_ENABLED: false
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      LEVEL_TYPE: "terra:overworld/overworld"
      ALLOW_FLIGHT: true
      SYNC_CHUNK_WRITES: true
      SIMULATION_DISTANCE: 8
      ENFORCE_SECURE_PROFILE: false
      # Server JVM options
      MEMORY: 4G
      ENABLE_ROLLING_LOGS: true
      TUNE_VIRTUALIZED: true
      TUNE_NURSERY_SIZES: true
      JAVA_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      # Auto-pause
      STOP_SERVER_ANNOUNCE_DELAY: 10
      ENABLE_AUTOPAUSE: true
    volumes:
      - ~/mangoplex-smp/data:/data