services:
  mc:
    image: itzg/minecraft-server:java17-graalvm-ce
    restart: "always"
    ports:
      - "25565:25565"
    environment:
      # Whitelist
      WHITELIST: "05f9e15f-4ed3-4ecd-b7f7-b9ad1f0a8e58,88abe932-7628-4636-937f-1549a9dc4993,ea56242b-d809-407d-991a-09db0ee7a660,19469d5c-3619-4ca9-b4a7-e002df05ae70,c7df62f1-e10a-4151-a2af-c3def82b1b8f,3c1306b6-3604-46e4-9bbf-b49bfdfa9643,2440be0d-38a6-4759-a907-f6422d1dbc42,b2a12a5e-e49e-4c94-9ccc-e7a162f51e8a"
      # Mods and datapacks
      VANILLATWEAKS_SHARECODE: "VEc2PR,d4Xleu"
      DATAPACKS: "https://cdn-raw.modrinth.com/data/HSfsxuTo/versions/kn0j4TYn/explorify-1.19-1.3.0.zip,https://cdn-raw.modrinth.com/data/5y2R1ofr/versions/FvKsx2Xt/mine-treasure-1.1.4.zip,https://cdn-raw.modrinth.com/data/7tKn1fLd/versions/lT2eggeo/MobCaptains-v2.0.1.zip,https://static.planetminecraft.com/files/resource_media/datapack/fisherman-1-4-1.zip"
      INITIAL_ENABLED_PACKS: "update_1_20,bundle,fabric"
      MODRINTH_PROJECTS: |
        fabric-api,no-chat-reports,
        alternate-current,rail-optimization,vmp-fabric,c2me-fabric,lithium,starlight,ferrite-core,memoryleakfix,krypton,
        terra:beta,fallingtree,
        apollos-additional-structures
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: false
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODS: "https://github.com/MangoPlex/smp/releases/latest/download/mangoplex-smp-mc${minecraftVersion}.jar,https://github.com/fxmorin/ExperimentalPerformance/releases/download/v0.1.0/experimentalPerformance-0.1.0.jar"
      # Auto-execute RCON commands
      RCON_CMDS_STARTUP: |-
        scoreboard players set in mt.common_chance 4000
        scoreboard players set in mt.rare_chance 12000
        scoreboard players set in mt.epic_chance 36000
        function mt:settings/disable_l
        gamerule disableElytraMovementCheck true
        gamerule playersSleepingPercentage 50
      # Server version
      VERSION: ${minecraftVersion}
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: ${loaderVersion}
      # Server properties
      EULA: true
      DIFFICULTY: hard
      FORCE_GAME_MODE: true
      SNOOPER_ENABLED: false
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      LEVEL_TYPE: "terra:overworld/overworld"
      ALLOW_FLIGHT: true
      SYNC_CHUNK_WRITES: true
      SIMULATION_DISTANCE: 8
      ENFORCE_SECURE_PROFILE: false
      MOTD: "MangoPlex SMP"
      # Server JVM options
      MEMORY: 4G
      ENABLE_ROLLING_LOGS: true
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:AllocatePrefetchStyle=3  -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:GCTimeRatio=99 -XX:+UseLargePages -XX:LargePageSizeInBytes=2m -XX:+EagerJVMCI -Dgraal.CompilerConfiguration=community"
      # Auto-pause
      STOP_SERVER_ANNOUNCE_DELAY: 10
      ENABLE_AUTOPAUSE: true
      AUTOPAUSE_TIMEOUT_EST: 1200
    volumes:
      - ~/mangoplex-smp/data:/data