name = "MangoPlex SMP"
author = "JustMango"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2087423d049d93a2a5b0f15ce81c0e49d55299e8fa20025d8da574772247a4e0"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
