name = "MangoPlex SMP"
author = "JustMango"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "453e9cd35207c265abeaf843ebb2878fe61499bd823643b5ec9a0b0b82dcba8a"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
