name = "Circus SMP"
author = "JustMango"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dfb36aa3c1e7d3c99e66dd068a0d77be45e34a9099997390d17c34ddf505812"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "data"
