name: Build and Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/fabric/fabric
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v1
        id: changelog
        with:
          context: changelog
          workflow_id: build_release.yml
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew checkVersion build github --stacktrace -Porg.gradle.parallel.threads=4